# Generated by Django 2.2.1 on 2019-06-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='courses',
            new_name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Student_image'),
        ),
    ]
