# Generated by Django 2.2.1 on 2019-10-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190613_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='place_of_recidance',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=30),
        ),
    ]
